#!/usr/bin/env bash
set -euo pipefail

# Package the Seedance 2.0 billing branch for customer delivery.
#
# Optional environment variables:
#   VERSION=2026-05-06-seedance-billing
#   BASE_REF=leia/main
#   OUTPUT_DIR=compliance/releases
#   GENERATE_SBOM=false

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "Working tree is dirty. Commit or stash changes before packaging." >&2
  exit 1
fi

HEAD_SHA="$(git rev-parse HEAD)"
SHORT_SHA="$(git rev-parse --short HEAD)"
VERSION="${VERSION:-seedance-2-billing-${SHORT_SHA}}"
BASE_REF="${BASE_REF:-leia/main}"
OUTPUT_DIR="${OUTPUT_DIR:-${ROOT_DIR}/compliance/releases}"
RELEASE_DIR="${OUTPUT_DIR}/${VERSION}"

mkdir -p "${RELEASE_DIR}"

write_sha256_line() {
  local file="$1"
  local relative_file
  relative_file="$(basename "${file}")"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "${file}" | awk -v name="${relative_file}" '{print $1 "  " name}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "${file}" | awk -v name="${relative_file}" '{print $1 "  " name}'
  elif command -v openssl >/dev/null 2>&1; then
    openssl dgst -sha256 "${file}" | awk -v name="${relative_file}" '{print $NF "  " name}'
  else
    echo "sha256sum, shasum, or openssl is required to generate checksums." >&2
    return 1
  fi
}

generate_release_checksums() {
  local checksum_file="${RELEASE_DIR}/SHA256SUMS"
  : >"${checksum_file}"
  while IFS= read -r file; do
    write_sha256_line "${file}" >>"${checksum_file}"
  done < <(find "${RELEASE_DIR}" -maxdepth 1 -type f ! -name 'SHA256SUMS' | sort)
}

SOURCE_ARCHIVE="${RELEASE_DIR}/new-api-${VERSION}-source.tar.gz"
git archive --format=tar.gz --prefix="new-api-${VERSION}/" --output="${SOURCE_ARCHIVE}" HEAD

{
  echo "# Seedance 2.0 Billing Delivery Manifest"
  echo
  echo "- Version: ${VERSION}"
  echo "- Commit: ${HEAD_SHA}"
  echo "- Base ref: ${BASE_REF}"
  echo "- Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo
  echo "## Required Customer Delivery Artifacts"
  echo
  echo "1. Source archive: $(basename "${SOURCE_ARCHIVE}")"
  echo "2. License: LICENSE"
  echo "3. AGPL checklist: compliance/AGPL_COMPLIANCE.md"
  echo "4. Seedance billing plan: docs/SEEDANCE_2_BILLING_PLAN.md"
  echo "5. Acceptance runbook: docs/SEEDANCE_2_BILLING_ACCEPTANCE.md"
  echo "6. Remaining tasks: docs/SEEDANCE_2_BILLING_REMAINING_TASKS.md"
  echo "7. Self-service billing API and UI: /api/billing/self/* and /console/topup '我的 Seedance 账单'"
  echo "8. Production preflight: scripts/seedance-billing-preflight.sh"
  echo "9. Smoke test: scripts/seedance-billing-smoke.sh"
  echo "10. Evidence collector: scripts/seedance-billing-collect-evidence.sh"
  echo "11. Evidence verifier: scripts/seedance-billing-verify-evidence.sh"
  echo "12. Monitoring runbook: docs/SEEDANCE_2_MONITORING.md"
  echo "13. Prometheus scrape example: deploy/observability/seedance-billing-prometheus.yml"
  echo "14. Prometheus alert rules: deploy/observability/seedance-billing-alert-rules.yml"
  echo "15. Grafana dashboard: deploy/observability/seedance-billing-grafana-dashboard.json"
  echo "16. Checksums: SHA256SUMS"
  echo "17. SBOM: sbom.spdx.json, if generated for this release"
  echo
  echo "## Acceptance Evidence Notes"
  echo
  echo "- Collect admin billing evidence with ADMIN_ACCESS_TOKEN and ADMIN_USER_ID."
  echo "- Collect customer self-service billing evidence with SELF_ACCESS_TOKEN and SELF_USER_ID."
  echo "- Verify self-service evidence with scripts/seedance-billing-verify-evidence.sh; it checks that self billing rows only contain self_user_id."
  echo
  echo "## Branch Change Log"
  echo
  if git rev-parse --verify "${BASE_REF}" >/dev/null 2>&1; then
    git log --oneline --decorate "${BASE_REF}..HEAD"
  else
    echo "Base ref ${BASE_REF} not found locally. Run: git fetch --all --prune"
  fi
} >"${RELEASE_DIR}/DELIVERY_MANIFEST.md"

if [[ "${GENERATE_SBOM:-false}" == "true" ]]; then
  "${ROOT_DIR}/scripts/generate-sbom.sh" "${RELEASE_DIR}/sbom.spdx.json"
else
  cat >"${RELEASE_DIR}/SBOM_NOT_GENERATED.txt" <<EOF
SBOM was not generated by this packaging run.

To generate it for this exact release, run:

  GENERATE_SBOM=true VERSION=${VERSION} BASE_REF=${BASE_REF} scripts/package-seedance-delivery.sh

or:

  scripts/generate-sbom.sh ${RELEASE_DIR}/sbom.spdx.json
EOF
fi

generate_release_checksums

echo "Delivery package generated at ${RELEASE_DIR}"
echo "Checksums written to ${RELEASE_DIR}/SHA256SUMS"
