package controller

import (
	"fmt"
	"net/http"
	"strconv"
	"strings"

	"github.com/QuantumNous/new-api/common"
	"github.com/QuantumNous/new-api/model"

	"github.com/gin-gonic/gin"
)

type prometheusLabel struct {
	Name  string
	Value string
}

type prometheusMetric struct {
	Name   string
	Help   string
	Value  float64
	Labels []prometheusLabel
}

func prometheusLabelValue(value string) string {
	replacer := strings.NewReplacer(
		`\`, `\\`,
		"\n", `\n`,
		`"`, `\"`,
	)
	return replacer.Replace(value)
}

func formatPrometheusLabels(labels []prometheusLabel) string {
	filtered := make([]string, 0, len(labels))
	for _, label := range labels {
		if strings.TrimSpace(label.Name) == "" || label.Value == "" {
			continue
		}
		filtered = append(filtered, fmt.Sprintf(`%s="%s"`, label.Name, prometheusLabelValue(label.Value)))
	}
	if len(filtered) == 0 {
		return ""
	}
	return "{" + strings.Join(filtered, ",") + "}"
}

func appendPrometheusMetric(builder *strings.Builder, metric prometheusMetric) {
	builder.WriteString("# HELP ")
	builder.WriteString(metric.Name)
	builder.WriteByte(' ')
	builder.WriteString(metric.Help)
	builder.WriteByte('\n')
	builder.WriteString("# TYPE ")
	builder.WriteString(metric.Name)
	builder.WriteString(" gauge\n")
	builder.WriteString(metric.Name)
	builder.WriteString(formatPrometheusLabels(metric.Labels))
	builder.WriteByte(' ')
	builder.WriteString(strconv.FormatFloat(metric.Value, 'f', -1, 64))
	builder.WriteByte('\n')
}

func billingPrometheusLabels(filter model.BillingAlertFilter) []prometheusLabel {
	channelID := ""
	if filter.Channel > 0 {
		channelID = strconv.Itoa(filter.Channel)
	}
	userID := ""
	if filter.UserId > 0 {
		userID = strconv.Itoa(filter.UserId)
	}
	return []prometheusLabel{
		{Name: "model_name", Value: filter.ModelName},
		{Name: "billing_source", Value: filter.BillingSource},
		{Name: "group", Value: filter.Group},
		{Name: "channel_id", Value: channelID},
		{Name: "user_id", Value: userID},
	}
}

func formatBillingPrometheusMetrics(metrics *model.BillingAlertMetrics, filter model.BillingAlertFilter) string {
	labels := billingPrometheusLabels(filter)
	builder := strings.Builder{}
	builder.WriteString("# Generated by NewAPI billing metrics exporter.\n")
	appendPrometheusMetric(&builder, prometheusMetric{Name: "newapi_billing_window_start_timestamp", Help: "Billing metric window start timestamp in seconds.", Value: float64(metrics.WindowStart), Labels: labels})
	appendPrometheusMetric(&builder, prometheusMetric{Name: "newapi_billing_window_end_timestamp", Help: "Billing metric window end timestamp in seconds.", Value: float64(metrics.WindowEnd), Labels: labels})
	appendPrometheusMetric(&builder, prometheusMetric{Name: "newapi_billing_consume_quota", Help: "Total consumed quota in the selected billing window.", Value: float64(metrics.ConsumeQuota), Labels: labels})
	appendPrometheusMetric(&builder, prometheusMetric{Name: "newapi_billing_refund_quota", Help: "Total refunded quota in the selected billing window.", Value: float64(metrics.RefundQuota), Labels: labels})
	appendPrometheusMetric(&builder, prometheusMetric{Name: "newapi_billing_net_quota", Help: "Net consumed quota after refunds in the selected billing window.", Value: float64(metrics.NetQuota), Labels: labels})
	appendPrometheusMetric(&builder, prometheusMetric{Name: "newapi_billing_request_count", Help: "Number of consume billing records in the selected billing window.", Value: float64(metrics.RequestCount), Labels: labels})
	appendPrometheusMetric(&builder, prometheusMetric{Name: "newapi_billing_refund_count", Help: "Number of refund billing records in the selected billing window.", Value: float64(metrics.RefundCount), Labels: labels})
	appendPrometheusMetric(&builder, prometheusMetric{Name: "newapi_billing_refund_rate", Help: "Refund record ratio in the selected billing window.", Value: metrics.RefundRate, Labels: labels})
	appendPrometheusMetric(&builder, prometheusMetric{Name: "newapi_billing_task_success_count", Help: "Number of successful asynchronous tasks in the selected billing window.", Value: float64(metrics.TaskSuccessCount), Labels: labels})
	appendPrometheusMetric(&builder, prometheusMetric{Name: "newapi_billing_task_failure_count", Help: "Number of failed asynchronous tasks in the selected billing window.", Value: float64(metrics.TaskFailureCount), Labels: labels})
	appendPrometheusMetric(&builder, prometheusMetric{Name: "newapi_billing_task_failure_rate", Help: "Asynchronous task failure ratio in the selected billing window.", Value: metrics.TaskFailureRate, Labels: labels})
	appendPrometheusMetric(&builder, prometheusMetric{Name: "newapi_billing_pending_task_count", Help: "Number of asynchronous tasks not yet in a final status.", Value: float64(metrics.PendingTaskCount), Labels: labels})
	appendPrometheusMetric(&builder, prometheusMetric{Name: "newapi_billing_timed_out_task_count", Help: "Number of asynchronous tasks older than the configured timeout and not yet final.", Value: float64(metrics.TimedOutTaskCount), Labels: labels})
	appendPrometheusMetric(&builder, prometheusMetric{Name: "newapi_billing_worker_lag_seconds", Help: "Age of the oldest non-final task update in seconds.", Value: float64(metrics.WorkerLagSeconds), Labels: labels})
	appendPrometheusMetric(&builder, prometheusMetric{Name: "newapi_billing_insufficient_balance_count", Help: "Number of balance or subscription quota shortage signals.", Value: float64(metrics.InsufficientBalanceCount), Labels: labels})
	appendPrometheusMetric(&builder, prometheusMetric{Name: "newapi_billing_upstream_error_count", Help: "Number of upstream error task failures.", Value: float64(metrics.UpstreamErrorCount), Labels: labels})
	appendPrometheusMetric(&builder, prometheusMetric{Name: "newapi_billing_alert_count", Help: "Number of active billing alerts.", Value: float64(len(metrics.Alerts)), Labels: labels})

	for _, alert := range metrics.Alerts {
		alertLabels := append([]prometheusLabel{}, labels...)
		alertLabels = append(alertLabels,
			prometheusLabel{Name: "alert_key", Value: alert.Key},
			prometheusLabel{Name: "severity", Value: alert.Severity},
		)
		appendPrometheusMetric(&builder, prometheusMetric{Name: "newapi_billing_alert_active", Help: "Active billing alert indicator by alert key and severity.", Value: 1, Labels: alertLabels})
	}
	return builder.String()
}

func GetBillingPrometheusMetrics(c *gin.Context) {
	filter := parseBillingAlertFilter(c)
	metrics, err := model.GetBillingAlertMetrics(filter)
	if err != nil {
		common.ApiError(c, err)
		return
	}
	c.Data(http.StatusOK, "text/plain; version=0.0.4; charset=utf-8", []byte(formatBillingPrometheusMetrics(metrics, filter)))
}
